### ISSUE TITLE
Target current workspace

### ISSUE THREAD

**Issue by gep13** [Odonno/new-cmd#1]
In the readme, you mention targetting the current workspace, which would suggest that the command window should open at the root of the folder that you have open.  Is that correct?  If so, that is not currently happening for me.

The command window opens at `C:\Users\<username>\.vscode\extensions\odonno.new-cmd>`

**Comment by Odonno** [comment]
It seems I used the wrong context.

**Comment by Odonno** [comment]
@gep13 Fixed !

**Comment by gep13** [comment]
Noice, seems to work now! :+1:
