### ISSUE TITLE
Custom console support

### ISSUE THREAD

**Issue by lukasz-wronski** [Odonno/new-cmd#4]
It would be nice if you'll add some sort of configuraion to this plugin that will allow to run terminal of your choice, for example I'd like to run Cmder instead of windows command prompt.

**Comment by Odonno** [comment]
Yep, that seems great.

I'll check if it's possible.

**Comment by lukasz-wronski** [comment]
It is. You can check your root folder path with vscode.workspace.rootPath, check if there is a config file you need with node 'fs' lib, load it with 'fs' and parse it with JSON.parse then use the value from config to run what user wants. 

It would be nice if you'll allow to use a pattern with predefined parameters so I can write something like  "Cmder.exe %rootPath" and the plugin will change %rootPath to the correct project path and then execute it :)

Remember that it's a good idea to keep config inside .vscode folder.

**Comment by Odonno** [comment]
Hi @lukasz-wronski 

It's been a while. I've updated the extension based on your feedback.

What do you think ?
